version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: node:9.11.1-alpine
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              awscli==1.15.8
      - run:
           name: Install ZIP
           command: |
            apk update \
            && apk add zip unzip \
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - attach_workspace:
          at: ~/app
      - run: npm install
      - run: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: |
            ls
            cd build/lib
            npm publish --access public
      - run:
          name: Deploying storybook to s3 bucket
          command: |
            ls
            cd ../../
            aws s3 sync storybook-static s3://storybook.bekk.no
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
              branches:
                only: master
              tags:
                only: /.*/