version: 2
jobs:
  build_and_deploy:
    environment:
      APP_NAME: komponent.bibliotek
    working_directory: /app
    docker:
      - image: circleci/node:9.11
    steps:
      - checkout
      - deploy:
          name: Deploy storybook to github pages
          command: |
              npm run deploy-storybook
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy:
          filters:
              branches:
                only: /.*/
              tags:
                only: /[0-9]+\.[0-9]+\.[0-9]+/